<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>nullable</WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\DataFac.Conduits.GrpcServer\DataFac.Conduits.GrpcServer.csproj" />
		<ProjectReference Include="..\..\Testing.Calculator\Testing.Calculator.csproj" />
		<ProjectReference Include="..\XApp1.ServiceDefaults\XApp1.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>
