<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DataFac.Conduits.HttpClient\DataFac.Conduits.HttpClient.csproj" />
    <ProjectReference Include="..\..\DataFac.Conduits.HttpCommon\DataFac.Conduits.HttpCommon.csproj" />
    <ProjectReference Include="..\..\Testing.Weather\Testing.Weather.csproj" />
    <ProjectReference Include="..\XApp1.ServiceDefaults\XApp1.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
