<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
	  <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.94">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataFac.Conduits.HttpCommon\DataFac.Conduits.HttpCommon.csproj" />
    <ProjectReference Include="..\DataFac.Conduits\DataFac.Conduits.csproj" />
  </ItemGroup>

</Project>
