<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>nullable</WarningsAsErrors>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Copyright>Copyright (c) 2020-2026 DataFac</Copyright>
		<Company>DataFac</Company>
		<Authors>DataFac Contributors</Authors>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>..\SigningKey.snk</AssemblyOriginatorKeyFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/datafac/conduits</RepositoryUrl>
		<PackageProjectUrl>https://github.com/datafac/conduits</PackageProjectUrl>
		<Description>Conduits http client</Description>
		<Title>Package title</Title>
		<Product>Conduits</Product>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="System.Net.Http.Json" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\DataFac.Conduits.HttpCommon\DataFac.Conduits.HttpCommon.csproj" />
	  <ProjectReference Include="..\DataFac.Conduits\DataFac.Conduits.csproj" />
	</ItemGroup>

</Project>
